# Generated by Django 3.1.1 on 2020-09-25 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favlist',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fav_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
